old_sound_rabbit_mq:
  connections:
    default:
      host:     '%env(RABBITMQ_HOST)%'
      port:     '%env(RABBITMQ_PORT)%'
      user:     '%env(RABBITMQ_USER)%'
      password: '%env(RABBITMQ_PASSWORD)%'
      vhost:    '/'
      lazy:     false
      connection_timeout: 3
      read_write_timeout: 3

      # requires php-amqplib v2.4.1+ and PHP5.4+
      keepalive: false

      # requires php-amqplib v2.4.1+
      heartbeat: 0
  consumers:
    log:
      connection:       default
      exchange_options: { name: 'log', type: direct }
      queue_options:    { name: 'log' }
      callback:         log_consumer
