controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

rabbit_send:
    path: /send
    controller: App\Controller\RabbitReceiverController::send

rabbit_receive:
    path: /receive
    controller: App\Controller\RabbitReceiverController::receive
